import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NavBar} from "@/app/ui_components/NavBar";
import React from "react";
import {AuthProvider} from "@/app/context/AuthContext";
import {Footer} from "@/app/ui_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en" data-theme={"light"}>
      <body className={inter.className}>
      <AuthProvider>
          <NavBar/>
          {children}
          <Footer/>
      </AuthProvider>
      </body>
    </html>
  );
}
